services:
  mysql:
    image: mysql:8
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rps@123
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./todo-backend/todo-backend
    container_name: todo-backend
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tododb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rps@123
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./todo-frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  mysql-data:


